// Turns a pinned bitwarden/clients checkout (GPL-3.0) into AZET Pass. Everything else stays byte-identical to upstream.
// What changes (each line is a PARITY row): R-numbers are in ~/Code/azet-suite/reference/azet-pass/PARITY.md.
//  - no commercially licensed code: bitwarden_license/ and @bitwarden/commercial-sdk-internal are removed (OSS build)
//  - default server: the one production region is https://pass.azet.io (our Cloudflare Worker)
//  - name: "Bitwarden" -> "AZET Pass" in every UI string table (trademark; file-and-sentence rule c)
//  - logo, shield mark and toolbar/app icons: our key mark in the same slots and pixel sizes (c)
//  - 변형 축: the item view shows TOTP codes without Premium
// usage: node rebrand.mjs <clients-checkout>
import fs from 'node:fs'
import path from 'node:path'

const root = path.resolve(process.argv[2])
const here = path.dirname(new URL(import.meta.url).pathname)
const p = (...a) => path.join(root, ...a)
const edit = (file, fn) => {
  const before = fs.readFileSync(p(file), 'utf8')
  const after = fn(before)
  if (after === before) throw new Error(`rebrand: no change in ${file} (upstream moved?)`)
  fs.writeFileSync(p(file), after)
}
const BASE = 'https://pass.azet.io'

// 1. OSS only
fs.rmSync(p('bitwarden_license'), { recursive: true, force: true })
fs.writeFileSync(p('package.json'), fs.readFileSync(p('package.json'), 'utf8').replace(/\n\s*"@bitwarden\/commercial-sdk-internal": "[^"]*",/, ''))

// 2. default server
edit('libs/common/src/platform/services/default-environment.service.ts', (s) =>
  s.replace(/export const PRODUCTION_REGIONS: RegionConfig\[\] = \[[\s\S]*?\n\];/, `export const PRODUCTION_REGIONS: RegionConfig[] = [
  {
    key: Region.US,
    domain: "pass.azet.io",
    urls: {
      base: null,
      api: "${BASE}/api",
      identity: "${BASE}/identity",
      icons: "${BASE}/icons",
      webVault: "${BASE}",
      notifications: "${BASE}/notifications",
      events: "${BASE}/events",
      scim: null,
      send: "${BASE}/#/send/",
    },
  },
];`))

// 3. name in every string table (values only; keys, placeholders and URLs untouched)
const tables = ['apps/browser/src/_locales', 'apps/desktop/src/locales', 'apps/web/src/locales']
let renamed = 0
const KO_EXTRA = JSON.parse(fs.readFileSync(path.join(here, 'brand/ko-extra.json'), 'utf8'))
// [English, Korean]; other languages get the English line (a right fact in English beats a wrong one in German)
const SUPPORT = 'hello@azet.io'
const OVR = {
  authenticatorAppDescV2: ['Enter a code generated by an authenticator app such as Google Authenticator or Microsoft Authenticator.', 'Google Authenticator, Microsoft Authenticator 같은 인증 앱에 표시된 코드를 입력하세요.'],
  twoStepContinueToBitwardenUrlTitle: ['Open this page?', '이 페이지를 열까요?'],
  twoStepContinueToBitwardenUrlDesc: ['The page opens in a new tab.', '새 탭에서 열립니다.'],
  couldNotDecryptVaultItem: [`AZET Pass could not decrypt the vault item listed below. Email ${SUPPORT} with the item ID below to see if it can be recovered.`, `AZET Pass가 아래 보관함 항목을 해독하지 못했습니다. 아래 항목 ID를 ${SUPPORT}로 보내 주시면 복구할 수 있는지 확인해 드립니다.`],
  couldNotDecryptVaultItems: [`AZET Pass could not decrypt the vault items listed below. Email ${SUPPORT} with the item IDs below to see if they can be recovered.`, `AZET Pass가 아래 보관함 항목들을 해독하지 못했습니다. 아래 항목 ID를 ${SUPPORT}로 보내 주시면 복구할 수 있는지 확인해 드립니다.`],
  userApiKeyDesc: ['Your API key signs the command-line client (bw, with "bw config server https://pass.azet.io") in to your account.', 'API 키로 명령줄 클라이언트(bw, "bw config server https://pass.azet.io" 설정 뒤)에 로그인할 수 있습니다.'],
  continueToBitwardenDotCom: ['Continue to the AZET Pass web vault?', 'AZET Pass 웹 보관함으로 이동할까요?'],
  premiumManageAlert: ['You can manage your membership in the AZET Pass web vault. Do you want to visit the website now?', 'AZET Pass 웹 보관함에서 멤버십을 관리할 수 있습니다. 지금 웹사이트로 이동할까요?'],
  downloadFromBitwardenNow: ['Download from azet.io', 'azet.io에서 받기'],
  getTheMobileAppDesc: ['AZET Pass for Android is on azet.io. Scan the code with your phone or open the link below.', 'Android용 AZET Pass는 azet.io에서 받습니다. 휴대폰으로 코드를 찍거나 아래 링크를 여세요.'],
  emailPlaceholder: ['user@example.com , user@acme.com', 'user@example.com , user@acme.com'],
  emailPlaceholderMultiple: ['user@example.com, user@acme.com', 'user@example.com, user@acme.com'],
  selfHostedBaseUrlHint: ['Specify the base URL of your on-premises hosted server. Example: https://vault.example.com', '직접 운영하는 서버의 기본 URL을 입력하세요. 예: https://vault.example.com'],
  continueToHelpCenterDesc: ['Learn more about using AZET Pass on the help page.', '도움말 페이지에서 AZET Pass 사용법을 더 알아보세요.'],
}
// new keys for the Premium benefits our server really gives (web vault Premium page)
const AZ_KEYS = {
  en: { azetPremiumReports: { message: 'Password health reports: exposed, reused and weak passwords' }, azetPremiumFileSend: { message: 'File Send' }, azetPremiumArchive: { message: 'Archive items out of your vault list' } },
  ko: { azetPremiumReports: { message: '비밀번호 점검 보고서: 유출·재사용·약한 비밀번호' }, azetPremiumFileSend: { message: '파일 Send' }, azetPremiumArchive: { message: '항목 보관(목록에서 치워 두기)' } },
}
for (const dir of tables.map((d) => p(d)).filter(fs.existsSync)) {
  for (const lang of fs.readdirSync(dir)) {
    const f = path.join(dir, lang, 'messages.json')
    if (!fs.existsSync(f)) continue
    const j = JSON.parse(fs.readFileSync(f, 'utf8'))
    const ko = lang === 'ko'
    // Upstream ko leaves sign-in, sign-up and empty-vault lines in English: fill only those still equal to English
    if (ko) {
      const en = JSON.parse(fs.readFileSync(path.join(dir, 'en', 'messages.json'), 'utf8')) // 'en' is read before 'ko'
      for (const [k, v] of Object.entries(KO_EXTRA))
        if (j[k] && en[k] && j[k].message.replaceAll('Bitwarden', 'AZET Pass') === en[k].message) j[k].message = v
    }
    for (const v of Object.values(j)) {
      if (typeof v?.message === 'string' && v.message.includes('Bitwarden')) {
        v.message = v.message.replaceAll('Bitwarden', 'AZET Pass')
        // Korean particles: 비트워든 ends in a consonant, 패스 in a vowel
        if (ko) v.message = v.message.replace(/AZET Pass(은|을|과|으로|이 )/g, (m, x) => 'AZET Pass' + { '은': '는', '을': '를', '과': '와', '으로': '로', '이 ': '가 ' }[x])
        renamed++
      }
    }
    // Ready-zero (lane 98): lines that name products we do not have or promise what our server does not do
    for (const [k, [enMsg, koMsg]] of Object.entries(OVR)) if (j[k]) j[k].message = ko ? koMsg : enMsg
    for (const k of ['maxFileSize', 'maxFileSizeSansPunctuation']) if (j[k]) j[k].message = j[k].message.replace(/500\s?MB/, '25 MB') // KV value limit
    if (!j.azetPremiumReports) Object.assign(j, AZ_KEYS[ko ? 'ko' : 'en'])
    fs.writeFileSync(f, JSON.stringify(j, null, 2) + '\n')
  }
}
for (const m of ['apps/browser/src/manifest.json', 'apps/browser/src/manifest.v3.json']) {
  edit(m, (s) => s.replace('"id": "{446900e4-71c2-419f-a6a7-df9c091e268b}"', '"id": "pass@azet.io"').replaceAll('"Bitwarden Inc."', '"AZET LLC"').replace('"https://bitwarden.com"', '"https://azet.io"').replaceAll('"Bitwarden"', '"AZET Pass"'))
}
// Firefox built-in data consent (required for new add-ons since 2025-11-03; the key needs Firefox 140). What reaches
// pass.azet.io: the encrypted vault (logins, cards, identities), the account email, the sites saved in logins and the
// icon requests for them; client name, version and device type ride on every request (that type can only be optional).
edit('apps/browser/src/manifest.json', (s) => s.replace('"strict_min_version": "91.0"\n', `"strict_min_version": "140.0",
      "data_collection_permissions": {
        "required": ["authenticationInfo", "personallyIdentifyingInfo", "financialAndPaymentInfo", "browsingActivity"],
        "optional": ["technicalAndInteraction"]
      }\n`))

// 4. logo and mark in the same SVG slots (class names kept so theme colours apply as upstream)
const MARK = 'M13 1a8 8 0 1 1 0 16a8 8 0 0 1 0-16Zm0 5a3 3 0 1 0 0 6a3 3 0 0 0 0-6ZM11 16h4v15h-4ZM15 21h5v3.5h-5ZM15 26.5h4v3.5h-4Z'
const wm = JSON.parse(fs.readFileSync(path.join(here, 'brand/generated/wordmark.json'), 'utf8')) // "AZET Pass", 34 high
const pm = JSON.parse(fs.readFileSync(path.join(here, 'brand/generated/wordmark-pm.json'), 'utf8')) // "Password Manager"
// mark (26x32) at the left, wordmark after it, both scaled to the slot height; classes kept so theme colours apply
const logo = (cls, w, h, title, sub) => {
  const k = sub ? h * 0.62 / 34 : h / 34 // wordmark scale
  const m = (sub ? h * 0.66 : h) / 32 // mark scale
  const x = 26 * m + h * 0.2
  let body = `<path class="${cls}" fill-rule="evenodd" transform="scale(${m.toFixed(4)})" d="${MARK}"/>` +
    `<path class="${cls}" transform="translate(${x.toFixed(2)} 0) scale(${k.toFixed(4)})" d="${wm.path}"/>`
  if (sub) body += `<path class="${cls}" transform="translate(${x.toFixed(2)} ${(h * 0.6).toFixed(2)}) scale(${(h * 0.36 / 34).toFixed(4)})" d="${pm.path}"/>`
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" fill="none"><title>${title}</title>${body}</svg>`
}
const putSvg = (file, svgText) => edit(file, (s) => s.replace(/<svg[\s\S]*?<\/svg>/, svgText))
const svgs = 'libs/assets/src/svg/svgs/'
putSvg(svgs + 'bitwarden-logo.icon.ts', logo('tw-fill-marketing-logo', 290, 45, 'AZET Pass'))
putSvg(svgs + 'bitwarden-logo-beta.icon.ts', logo('tw-fill-marketing-logo', 120, 18, 'AZET Pass Beta'))
putSvg(svgs + 'password-manager.ts', logo('tw-fill-fg-nav', 200, 49, 'AZET Pass Password Manager', true))
putSvg(svgs + 'side-nav-logo.ts', logo('tw-fill-fg-nav', 153, 24, 'AZET Pass'))
putSvg(svgs + 'side-nav-logo-beta.ts', logo('tw-fill-fg-nav', 154, 24, 'AZET Pass Beta'))
putSvg(svgs + 'bitwarden-icon.ts', `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="none"><rect class="tw-fill-bw-blue" width="20" height="20" rx="3"/><path fill="#fff" fill-rule="evenodd" transform="translate(5.1 2) scale(0.5)" d="${MARK}"/></svg>`)
edit('libs/assets/src/svg/svgs/shield.ts', (s) =>
  s.replace(/<svg[\s\S]*?<\/svg>/, `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26 32" fill="none">
    <path class="tw-fill-fg-nav" fill-rule="evenodd" d="${MARK}"/>
  </svg>`))

// 5. toolbar icons, same file names and sizes as upstream
const img = p('apps/browser/src/images')
const tmp = path.join(here, 'brand/generated')
const sizes = new Set()
for (const f of fs.readdirSync(img)) {
  const m = f.match(/^icon(\d+)(_gray|_locked)?(_beta)?\.png$/)
  if (!m) continue
  sizes.add(m[1])
  const kind = m[2] === '_gray' ? 'gray' : m[2] === '_locked' ? 'locked' : 'blue'
  fs.copyFileSync(path.join(tmp, `${kind}-${m[1]}.png`), path.join(img, f))
}

// 5b. desktop app identity, update feed and icons (same files and sizes as upstream)
const eb = 'apps/desktop/electron-builder.json'
if (fs.existsSync(p(eb))) {
  const j = JSON.parse(fs.readFileSync(p(eb), 'utf8'))
  j.extraMetadata.name = 'azet-pass'
  j.productName = 'AZET Pass'
  j.appId = 'io.azet.pass'
  j.copyright = 'Copyright © 2015-2026 Bitwarden Inc. and contributors (GPL-3.0); AZET Pass changes © 2026 AZET LLC'
  j.publish = { provider: 'generic', url: `${BASE}/desktop` } // update feed on our server (Bitwarden: artifacts.bitwarden.com)
  // Microsoft Store identity: Partner Center > AZET Pass (9NF3686MBT1N) > Product identity
  Object.assign(j.appx, { applicationId: 'azetpass', identityName: 'AZET.ioSoftware.AZETPass',
    publisher: 'CN=FD00C6AE-19A7-454C-8593-06EEFB12B464', publisherDisplayName: 'AZET.io Software',
    minVersion: '10.0.17763.0', maxVersionTested: '10.0.26100.0' }) // the Store refuses MinVersion <= 10.0.17134.0
  const am = 'apps/desktop/custom-appx-manifest.xml' // the Appx template build-msix.sh fills (same as Bitwarden's appx-cross-build.ps1)
  edit(am, (s) => s.replace('<uap:DisplayName>Bitwarden</uap:DisplayName>', '<uap:DisplayName>AZET Pass</uap:DisplayName>'))
  fs.writeFileSync(p(eb), JSON.stringify(j, null, 2) + '\n')
  const res = p('apps/desktop/resources')
  const big = path.join(here, 'brand/generated') // made by brand/make-icons.sh (+ iconutil, magick); committed so CI needs no Mac tools
  for (const f of ['icon.icns', 'dmg.icns', 'icon.beta.icns', 'dmg.beta.icns']) fs.copyFileSync(path.join(big, 'icon.icns'), path.join(res, f))
  for (const f of ['icon.png', 'icon.beta.png']) fs.copyFileSync(path.join(big, 'blue-1024.png'), path.join(res, f))
  for (const f of ['icon.ico', 'icon.beta.ico']) fs.copyFileSync(path.join(big, 'icon.ico'), path.join(res, f))
  for (const dir of ['icons', 'icons_beta']) {
    for (const f of fs.readdirSync(path.join(res, dir))) {
      const m = f.match(/^(\d+)x\1\.png$/)
      if (m && fs.existsSync(path.join(big, `blue-${m[1]}.png`))) fs.copyFileSync(path.join(big, `blue-${m[1]}.png`), path.join(res, dir, f))
    }
  }
  for (const f of fs.readdirSync(path.join(big, 'appx'))) fs.copyFileSync(path.join(big, 'appx', f), path.join(res, 'appx', f))
}

// 6. 변형 축: TOTP code in the item view on the free plan (Bitwarden: Premium only). Server side, every item
//    already carries organizationUseTotp=true, which opens the copy and autofill gates.
edit('libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html', (s) => {
  const a = s.indexOf('@if (cipher.login.totp) {')
  const b = s.indexOf('</bit-form-field>', a)
  return s.slice(0, a) + s.slice(a, b).replace(/\(isPremium\$ \| async\)/g, '(totpFree$ | async)') + s.slice(b)
})
edit('libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts', (s) =>
  s.replace('  showPasswordCount: boolean = false;', '  // AZET 변형 축: verification codes are on the free plan\n  readonly totpFree$ = of(true);\n  showPasswordCount: boolean = false;')
   .replace(/import \{([^}]*)\} from "rxjs";/, (m, names) => names.includes(' of') || names.includes('of,') ? m : `import {${names.trimEnd()}, of } from "rxjs";`))

// ...and TOTP leaves the extension's list of Premium benefits
const prem = 'apps/browser/src/billing/popup/settings/premium-v2.component.html'
if (fs.existsSync(p(prem))) edit(prem, (s) => s.replace(/\s*<li>\s*\{\{ "premiumSignUpTotp" \| i18n \}\}\s*<\/li>/, ''))

// Windows cross-build from a Mac: we ship NSIS/portable only, so the Appx tool install (brew msix-packaging) is skipped
const nb = 'apps/desktop/desktop_native/build.js'
if (fs.existsSync(p(nb))) edit(nb, (s) => s.replace(/runCommand\("brew", \["install", "iinuwa\/msix-packaging-tap\/msix-packaging", "osslsigncode"\]\);/, '// AZET: no Appx packaging, so the msix/osslsigncode tools are not installed'))

// GPL-3.0 source offer where the reference shows its copyright line
const SRC = 'https://github.com/neulketing/azet-pass'
const about = 'apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.html'
if (fs.existsSync(p(about))) edit(about, (s) => s.replace('<p>&copy; Bitwarden Inc. 2015-{{ year }}</p>', `<p>&copy; Bitwarden Inc. 2015-{{ year }}, AZET LLC. GPL-3.0, source: <a href="${SRC}" target="_blank" rel="noreferrer">github.com/neulketing/azet-pass</a></p>`))
const dabout = 'apps/desktop/src/main/menu/menu.about.ts'
if (fs.existsSync(p(dabout))) edit(dabout, (s) => s.replace('"\\nArchitecture " +\n          process.arch;', `"\\nArchitecture " +\n          process.arch +\n          "\\n\\n© Bitwarden Inc. 2015-${new Date().getFullYear()}, AZET LLC. GPL-3.0, source: ${SRC}";`))
// frontend-layout is the web shell; anon-layout draws the footer of the login and sign-up screens (web and extension)
for (const foot of ['apps/web/src/app/layouts/frontend-layout.component.html', 'libs/components/src/anon-layout/anon-layout.component.html'])
  if (fs.existsSync(p(foot))) edit(foot, (s) => s.replace('<div bitTypography="body2">&copy; {{ year }} Bitwarden Inc.</div>', `<div bitTypography="body2">&copy; {{ year }} Bitwarden Inc., AZET LLC. GPL-3.0, <a href="${SRC}" target="_blank" rel="noreferrer">source</a></div>`))

// Purchase path: Bitwarden sends a self-hosted user to its cloud billing; AZET Pass Premium is an AZET licence key sold
// on azet.io and entered through the same "Upload your license file" dialog (server: POST /api/accounts/license).
const shp = 'apps/web/src/app/billing/individual/premium/self-hosted-premium.component'
if (fs.existsSync(p(shp + '.ts'))) {
  edit(shp + '.ts', (s) => s.replace(/this\.environmentService\.cloudWebVaultUrl\$\.pipe\(\s*map\(\(url\) => `\$\{url\}\/#\/settings\/subscription\/premium`\),\s*\)/g, 'of("https://azet.io/products/pass#plans")'))
  edit(shp + '.html', (s) => s.replace('href="https://bitwarden.com/pricing/"', 'href="https://azet.io/products/pass#plans"'))
}

// Sign-up and sign-in on our server: consent links are our terms and privacy policy; the passkey and SSO buttons go,
// because the server has neither (a click ended in a 404 and an "unexpected error" toast).
const swap = (file, pairs) => fs.existsSync(p(file)) && edit(file, (s) => pairs.reduce((t, [a, b]) => t.replace(a, b), s))
const LEGAL = [['"https://bitwarden.com/terms/"', '"https://azet.io/terms"'], ['"https://bitwarden.com/privacy/"', '"https://azet.io/privacy#pass"']]
// ...and the marketing-mail opt-in goes too: we send no newsletter (its unsubscribe link was bitwarden.com/email-preferences)
swap('libs/auth/src/angular/registration/registration-start/registration-start.component.html', [...LEGAL, ['<bit-form-control *ngIf="!isSelfHost">', '<bit-form-control *ngIf="false">']])
swap('apps/desktop/src/main/menu/menu.help.ts', LEGAL)
swap('libs/auth/src/angular/login/login.component.html', [[/\n\s*<div class="tw-text-center">\{\{ "or" \| i18n \}\}<\/div>[\s\S]*?\{\{ "useSingleSignOn" \| i18n \}\}\s*<\/button>/, '']])
swap('apps/web/src/index.html', [['<title page-title>Bitwarden Web vault</title>', '<title page-title>AZET Pass Web vault</title>'],
  // browser bar = the page's top area (anon layout background-alt), not Bitwarden blue
  ['<meta name="theme-color" content="#175DDC" />', '<meta name="theme-color" content="#f9fafb" media="(prefers-color-scheme: light)" />\n    <meta name="theme-color" content="#0c111d" media="(prefers-color-scheme: dark)" />']])

// 8. Ready-zero (lane 98, ~/hermes/02_Projects/azet-pass-ready-zero): nothing a user can reach may end in an error, a
//    feature our server does not have, or a Bitwarden page/store. Numbers = rows of inventory-pass.md.
const PRODUCT = 'https://azet.io/products/pass'
const HELP = `${BASE}/help/` // clients/brand/help, copied into the web vault by build-web.sh
const W = 'apps/web/src/app/'
// #2 two-step login: only the authenticator app (server: Email, Duo, YubiKey and FIDO2 have no routes)
swap(W + 'auth/settings/two-factor/two-factor-setup.component.ts', [['return type === TwoFactorProviderType.OrganizationDuo;', 'return type !== TwoFactorProviderType.Authenticator; // AZET: the server supports the authenticator app only']])
// #3 log in with passkey (no WebAuthn login on the server)
swap(W + 'auth/settings/security/password-settings/password-settings.component.html', [['\n<app-webauthn-login-settings></app-webauthn-login-settings>', '']])
// #5 new-device login protection: our server sends no new-device codes, so there is nothing to turn off
swap(W + 'auth/settings/account/account.component.html', [[/\n\s*<ng-container>\s*<button\s*\*ngIf="verifyNewDeviceLogin"[\s\S]*?<\/ng-container>/, '']])
// #8 emergency access, #13 organizations: not on our server
swap(W + 'layouts/user-layout.component.html', [[/@if \(showEmergencyAccess\(\)\) \{/g, '@if (false) {'], ['@if (!singleOrgPolicyApplies()) {', '@if (false) {']])
swap(W + 'vault/individual-vault/vault-filter/components/vault-filter.component.ts', [['const addAction = !singleOrgPolicy', 'const addAction = false // AZET: no organizations\n']])
swap(W + 'layouts/org-switcher/org-switcher.component.html', [['@if (!hideNewButton && !vfo1Enabled()) {', '@if (false) {']])
// #14 product switcher: Secrets Manager and Admin Console are Bitwarden business products
swap(W + 'layouts/header/web-header.component.html', [['      <product-switcher></product-switcher>\n', '']])
swap(W + 'layouts/web-side-nav.component.html', [[/\s*<navigation-product-switcher \[variant\]="variant\(\)"><\/navigation-product-switcher>/, '']])
// #9 self-hosted subscription: the "cloud subscription" button pointed back at pass.azet.io itself
swap(W + 'billing/individual/subscription/self-hosted-account-subscription.component.html', [[/\s*<a\s+bitButton\s+buttonType="secondary"\s+\[href\]="cloudSubscriptionUrl\(\)"[\s\S]*?<\/a>/, '']])
// #10 #11 Premium page: the benefits our server gives, no Families plan (no organizations)
swap(W + 'billing/individual/premium/self-hosted-premium.component.html', [[/\s*<!-- Families Card -->[\s\S]*?<\/billing-pricing-card>\s*<\/div>/, ''], ['md:tw-grid-cols-2', 'md:tw-grid-cols-1 tw-max-w-md tw-mx-auto']])
swap(W + 'billing/individual/premium/self-hosted-premium.component.ts', [[/this\.i18nService\.t\("builtInAuthenticator"\),\s*this\.i18nService\.t\("secureFileStorage"\),\s*this\.i18nService\.t\("emergencyAccess"\),\s*this\.i18nService\.t\("breachMonitoring"\),\s*this\.i18nService\.t\("andMoreFeatures"\),/,
  'this.i18nService.t("secureFileStorage"),\n    this.i18nService.t("azetPremiumFileSend"),\n    this.i18nService.t("azetPremiumReports"),\n    this.i18nService.t("azetPremiumArchive"),']])
// #17 authenticator set-up: no Bitwarden Authenticator store buttons
swap(W + 'auth/settings/two-factor/two-factor-setup-authenticator.component.html', [
  [/\(click\)="launchBitwardenUrl\('https:\/\/bitwarden\.com\/products\/authenticator\/'\)"\s*>Bitwarden Authenticator<\/a/, `(click)="launchExternalUrl('https://support.google.com/accounts/answer/1066447')"\n          >Google Authenticator</a`],
  [/\s*<p class="tw-text-center">\s*<a\s+href="https:\/\/apps\.apple\.com\/ca\/app\/bitwarden-authenticator[\s\S]*?<\/p>/, '']])
// #18 #19 404 page, PWA manifest, icons, U2F facets
swap('apps/web/src/404.html', [['Page not found | Bitwarden Web vault', 'Page not found | AZET Pass Web vault'], ['alt="Bitwarden"', 'alt="AZET Pass"']])
swap('apps/web/src/manifest.json', [['"name": "Bitwarden Vault"', '"name": "AZET Pass"'], ['"theme_color": "#175DDC"', '"theme_color": "#f9fafb"'], ['"background_color": "#175DDC"', '"background_color": "#f9fafb"']])
swap('apps/web/src/app-id.json', [['"https://vault.bitwarden.com"', `"${BASE}"`]])
if (fs.existsSync(p('apps/web/src/images/icons'))) {
  const wi = path.join(here, 'brand/generated/web') // brand/make-icons.sh output, resized with magick (committed)
  for (const f of fs.readdirSync(wi)) fs.copyFileSync(path.join(wi, f), f === 'favicon.ico' ? p('apps/web/src/favicon.ico') : p('apps/web/src/images/icons', f))
}
// extension (#25 #26 #27 #28 #30)
const E = 'apps/browser/src/'
swap(E + 'tools/popup/settings/about-page/about-page-v2.component.html', [[/\s*<bit-item>\s*<button type="button" bit-item-content \(click\)="rate\(\)">[\s\S]*?<\/bit-item>/, '']])
swap(E + 'tools/popup/settings/settings-v2.component.html', [[/\s*<bit-item>\s*<a bit-item-content routerLink="\/more-from-bitwarden"[\s\S]*?<\/bit-item>/, '']])
swap(E + 'vault/popup/settings/download-bitwarden.component.html', [
  [/<div class="tw-flex tw-justify-center tw-gap-4">[\s\S]*?<\/div>\s*<\/bit-card>/, `<a class="tw-text-primary-600 tw-flex tw-justify-center tw-no-underline tw-gap-2 tw-items-center" href="${PRODUCT}" bitLink target="_blank" endIcon="bwi-external-link">{{ "downloadFromBitwardenNow" | i18n }}</a>\n  </bit-card>`],
  [/\s*<h2 class="tw-mt-6" bitTypography="h6">\s*\{\{ "getTheDesktopApp" \| i18n \}\}[\s\S]*?<\/bit-card>/, '']]) // desktop is not released
if (fs.existsSync(p(E + 'images/download-qr.png'))) fs.copyFileSync(path.join(here, 'brand/generated/download-qr.png'), p(E + 'images/download-qr.png')) // QR = azet.io/products/pass
swap(E + 'billing/popup/settings/premium-v2.component.html', ['premiumSignUpTwoStepOptions', 'premiumSignUpEmergency', 'premiumSignUpSupport', 'premiumSignUpFuture']
  .map((k) => [new RegExp(`\\s*<li>\\s*\\{\\{ "${k}" \\| i18n \\}\\}\\s*<\\/li>`), '']))
// biometric unlock in the browser needs the desktop app, which is not released
swap(E + 'auth/popup/settings/account-security.component.html', [['@if (!(sharedUnlockFeatureEnabled$ | async)) {\n            <bit-form-control [disableMargin]="!((pinEnabled$ | async) || this.form.value.pin)">\n              <input bitCheckbox id="biometric"',
  '@if (false) {\n            <bit-form-control [disableMargin]="!((pinEnabled$ | async) || this.form.value.pin)">\n              <input bitCheckbox id="biometric"']])

// #12 #15 #21 #22 #24 #29: every Bitwarden page, store listing and help link in shipped code -> ours. Callbacks
// (webauthn/duo/connector), images and test fixtures stay; assets.bitwarden.com (phishing list) and github are not touched.
const helpTopic = (slug) => {
  const t = [[/^import/, 'import'], [/^export/, 'export'], [/auto-?fill|uri-match|blocking-uris|fill-assist|keyboard-shortcuts|policies/, 'autofill'],
    [/two-step|lost-two-step/, 'two-step'], [/send/, 'send'], [/attachments/, 'attachments'], [/kdf|encryption-key|fingerprint|account-recovery/, 'encryption'],
    [/passkey/, 'passkeys'], [/website-icons/, 'icons'], [/reports|phishing/, 'reports'], [/searching-vault|managing-items/, 'items'],
    [/create-bitwarden-account|learning-center|onboarding/, 'start'], [/server-geographies/, 'server'], [/wasm/, 'browser'],
    [/emergency|collection|organization|families|secrets-manager|user-types|managing-users|transfer-ownership|claimed|licensing|automatic-confirmation|ssh-agent|environment-variables/, 'not-included']]
    .find(([re]) => re.test(slug))
  return HELP + (t ? '#' + t[1] : '')
}
const mapBw = (url) => {
  const u = new URL(url)
  const pth = u.pathname
  if (/^\/(webauthn-callback|duo-callback|connector|images\/|email-preferences)/.test(pth)) return url
  if (pth.startsWith('/help')) return helpTopic(pth.slice(6))
  if (pth.startsWith('/contact')) return 'https://azet.io/contact'
  if (pth.startsWith('/browser-start')) return HELP + '#start'
  if (pth.startsWith('/blog/how-do-passkeys-work')) return HELP + '#passkeys'
  if (/^\/(pricing|go\/start-premium)/.test(pth)) return PRODUCT + '#plans'
  return PRODUCT
}
const BW_URL = /https:\/\/(?:www\.)?bitwarden\.com(?![\w.-])(?:\/[^"'`\s)<>,]*)?/g
const STORE_URL = /https:\/\/(?:chromewebstore\.google\.com|chrome\.google\.com\/webstore)\/detail\/[\w-]+\/nngceckbapebfimnlniiiahkandclblb[^"'`\s)<>]*|https:\/\/addons\.mozilla\.org\/[\w-]+\/firefox\/addon\/bitwarden-password-manager\/[^"'`\s)<>]*|https:\/\/apps\.apple\.com\/[\w/-]*\/app\/bitwarden[\w-]*\/id\d+[^"'`\s)<>]*|https:\/\/addons\.opera\.com\/[\w/-]*bitwarden-free-password-manager\/[^"'`\s)<>]*|https:\/\/microsoftedge\.microsoft\.com\/addons\/detail\/jbkfoedolllekgbhcbcoahefnbanhhlh|https:\/\/play\.google\.com\/store\/apps\/details\?id=com\.(?:x8bit\.bitwarden|bitwarden\.authenticator)/g
let relinked = 0
const walkSrc = (d) => fs.readdirSync(d, { withFileTypes: true }).flatMap((e) =>
  e.name === 'node_modules' || e.name.startsWith('.') ? [] : e.isDirectory() ? walkSrc(path.join(d, e.name)) : [path.join(d, e.name)])
for (const dir of ['apps/web/src', 'apps/browser/src', 'apps/desktop/src', 'libs'].map((d) => p(d)).filter(fs.existsSync)) {
  for (const f of walkSrc(dir)) {
    if (!/\.(ts|html)$/.test(f) || /\.(spec|stories)\.ts$|\/(spec|test|tests|__tests__)\//.test(f)) continue
    const s = fs.readFileSync(f, 'utf8')
    if (!s.includes('bitwarden') && !s.includes('nngceckb') && !s.includes('jbkfoed')) continue
    const out = s.replace(STORE_URL, () => PRODUCT).replace(BW_URL, mapBw)
    if (out !== s) { fs.writeFileSync(f, out); relinked++ }
  }
}
console.log(`rebrand: ready-zero links rewritten in ${relinked} files`)

// 7. Theme: AZET family tokens (azet-suite design/dist, DESIGN-SPEC U10) on top of Bitwarden's colour variables, so every
//    component keeps its upstream layout. Brand blue -> AZET violet (solid #6a4ae6 / dark #9a82ff), greys -> AZET ink and
//    rules, dark surfaces -> ground #0c111d / card #161b26; buttons become pills. Korean keeps words whole.
const AZ_THEME = `
/* AZET Pass theme (rebrand.mjs section 7) */
:root {
  --color-brand-050: #f4f1ff; --color-brand-100: #ebe6ff; --color-brand-200: #d9d0ff; --color-brand-300: #bfb0ff;
  --color-brand-400: #9a82ff; --color-brand-500: #8467f5; --color-brand-600: #7456ef; --color-brand-700: #6a4ae6;
  --color-brand-700-rgb: 106, 74, 230; --color-brand-800: #5b3bd6; --color-brand-800-rgb: 91, 59, 214;
  --color-brand-900: #4a2fb0; --color-brand-950: #2a2350; --color-brand-950-rgb: 42, 35, 80;
  --color-gray-050: #f9fafb; --color-gray-100: #f2f4f7; --color-gray-200: #eaecf0; --color-gray-300: #d0d5dd;
  --color-gray-400: #98a2b3; --color-gray-500: #667085; --color-gray-600: #475467; --color-gray-700: #344054;
  --color-gray-800: #1d2939; --color-gray-900: #101828; --color-gray-950: #0c111d;
  --color-primary-100: 244 241 255; --color-primary-300: 191 176 255; --color-primary-600: 106 74 230; --color-primary-700: 91 59 214;
  --color-background-alt: 249 250 251; --color-background-alt2: 106 74 230; --color-background-alt3: 74 47 176; --color-background-alt4: 42 35 80;
  --color-text-main: 16 24 40; --color-text-muted: 102 112 133;
  --color-illustration-outline: 42 35 80; --color-illustration-bg-primary: 235 230 255; --color-illustration-bg-secondary: 217 208 255;
  --color-illustration-logo: 106 74 230; --color-marketing-logo: 106 74 230;
}
.theme_dark {
  --color-primary-100: 42 35 80; --color-primary-300: 91 59 214; --color-primary-600: 154 130 255; --color-primary-700: 173 153 255;
  --color-background: 22 27 38; --color-background-alt: 12 17 29; --color-background-alt2: 31 36 47; --color-background-alt3: 51 55 65; --color-background-alt4: 12 17 29;
  --color-text-main: 245 245 246; --color-text-muted: 148 150 156;
  --color-bg-primary: #161b26; --color-bg-secondary: #0c111d; --color-bg-tertiary: #0c111d; --color-bg-quaternary: #1f242f; --color-bg-inactive: #0c111d;
  --color-bg-brand-strong: #ad99ff;
  --color-illustration-outline: 154 130 255; --color-illustration-bg-primary: 42 35 80; --color-illustration-bg-secondary: 74 47 176;
}
html:lang(ko) body { word-break: keep-all; overflow-wrap: anywhere; }
`
edit('libs/components/src/tw-theme.css', (s) => s + AZ_THEME)
edit('libs/components/src/button/button.component.ts', (s) => s.replace('classes.push("tw-rounded-xl");', 'classes.push("tw-rounded-full"); // AZET: pill buttons'))

console.log(`rebrand: ${renamed} strings renamed, ${sizes.size} icon sizes, server ${BASE}`)
